// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: grpc_exercicio.proto

package proto_exercicio

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Exercicio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome      string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao string `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
	Materia   string `protobuf:"bytes,4,opt,name=materia,proto3" json:"materia,omitempty"`
	Ativo     bool   `protobuf:"varint,5,opt,name=ativo,proto3" json:"ativo,omitempty"`
}

func (x *Exercicio) Reset() {
	*x = Exercicio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exercicio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercicio) ProtoMessage() {}

func (x *Exercicio) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercicio.ProtoReflect.Descriptor instead.
func (*Exercicio) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{0}
}

func (x *Exercicio) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exercicio) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Exercicio) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Exercicio) GetMateria() string {
	if x != nil {
		return x.Materia
	}
	return ""
}

func (x *Exercicio) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

type CreateAlterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exercicio *Exercicio `protobuf:"bytes,1,opt,name=exercicio,proto3" json:"exercicio,omitempty"`
}

func (x *CreateAlterRequest) Reset() {
	*x = CreateAlterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAlterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlterRequest) ProtoMessage() {}

func (x *CreateAlterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlterRequest.ProtoReflect.Descriptor instead.
func (*CreateAlterRequest) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlterRequest) GetExercicio() *Exercicio {
	if x != nil {
		return x.Exercicio
	}
	return nil
}

type CreateAlterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateAlterResponse) Reset() {
	*x = CreateAlterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAlterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlterResponse) ProtoMessage() {}

func (x *CreateAlterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlterResponse.ProtoReflect.Descriptor instead.
func (*CreateAlterResponse) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAlterResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateAlterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exercicio *Exercicio `protobuf:"bytes,1,opt,name=exercicio,proto3" json:"exercicio,omitempty"`
	Status    bool       `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error     string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetExercicio() *Exercicio {
	if x != nil {
		return x.Exercicio
	}
	return nil
}

func (x *GetResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetSomesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetSomesRequest) Reset() {
	*x = GetSomesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSomesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSomesRequest) ProtoMessage() {}

func (x *GetSomesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSomesRequest.ProtoReflect.Descriptor instead.
func (*GetSomesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{5}
}

func (x *GetSomesRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetSomesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exercicios []*Exercicio `protobuf:"bytes,1,rep,name=exercicios,proto3" json:"exercicios,omitempty"`
	Status     bool         `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error      string       `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetSomesResponse) Reset() {
	*x = GetSomesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSomesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSomesResponse) ProtoMessage() {}

func (x *GetSomesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSomesResponse.ProtoReflect.Descriptor instead.
func (*GetSomesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{6}
}

func (x *GetSomesResponse) GetExercicios() []*Exercicio {
	if x != nil {
		return x.Exercicios
	}
	return nil
}

func (x *GetSomesResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetSomesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusServiceRequest) Reset() {
	*x = StatusServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusServiceRequest) ProtoMessage() {}

func (x *StatusServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusServiceRequest.ProtoReflect.Descriptor instead.
func (*StatusServiceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{9}
}

type StatusServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *StatusServiceResponse) Reset() {
	*x = StatusServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_exercicio_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusServiceResponse) ProtoMessage() {}

func (x *StatusServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_exercicio_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusServiceResponse.ProtoReflect.Descriptor instead.
func (*StatusServiceResponse) Descriptor() ([]byte, []int) {
	return file_grpc_exercicio_proto_rawDescGZIP(), []int{10}
}

func (x *StatusServiceResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *StatusServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_grpc_exercicio_proto protoreflect.FileDescriptor

var file_grpc_exercicio_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x78,
	0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x22, 0x7d, 0x0a, 0x09, 0x45, 0x78, 0x65, 0x72, 0x63,
	0x69, 0x63, 0x69, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x22, 0x4e, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x09,
	0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69,
	0x6f, 0x2e, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x52, 0x09, 0x65, 0x78, 0x65,
	0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x22, 0x43, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x1c, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x75, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x72,
	0x63, 0x69, 0x63, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x45, 0x78,
	0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x52, 0x09, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63,
	0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x7c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6d, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x78, 0x65,
	0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e,
	0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x72, 0x63,
	0x69, 0x63, 0x69, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x15,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x32, 0x85, 0x04, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45,
	0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x12, 0x55, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63,
	0x69, 0x63, 0x69, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x54, 0x0a, 0x05, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x53, 0x6f, 0x6d, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x78,
	0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6d,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65,
	0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65,
	0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x0d, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69,
	0x63, 0x69, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_grpc_exercicio_proto_rawDescOnce sync.Once
	file_grpc_exercicio_proto_rawDescData = file_grpc_exercicio_proto_rawDesc
)

func file_grpc_exercicio_proto_rawDescGZIP() []byte {
	file_grpc_exercicio_proto_rawDescOnce.Do(func() {
		file_grpc_exercicio_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_exercicio_proto_rawDescData)
	})
	return file_grpc_exercicio_proto_rawDescData
}

var file_grpc_exercicio_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grpc_exercicio_proto_goTypes = []interface{}{
	(*Exercicio)(nil),             // 0: proto_exercicio.Exercicio
	(*CreateAlterRequest)(nil),    // 1: proto_exercicio.CreateAlterRequest
	(*CreateAlterResponse)(nil),   // 2: proto_exercicio.CreateAlterResponse
	(*GetRequest)(nil),            // 3: proto_exercicio.GetRequest
	(*GetResponse)(nil),           // 4: proto_exercicio.GetResponse
	(*GetSomesRequest)(nil),       // 5: proto_exercicio.GetSomesRequest
	(*GetSomesResponse)(nil),      // 6: proto_exercicio.GetSomesResponse
	(*DeleteRequest)(nil),         // 7: proto_exercicio.DeleteRequest
	(*DeleteResponse)(nil),        // 8: proto_exercicio.DeleteResponse
	(*StatusServiceRequest)(nil),  // 9: proto_exercicio.StatusServiceRequest
	(*StatusServiceResponse)(nil), // 10: proto_exercicio.StatusServiceResponse
}
var file_grpc_exercicio_proto_depIdxs = []int32{
	0,  // 0: proto_exercicio.CreateAlterRequest.exercicio:type_name -> proto_exercicio.Exercicio
	0,  // 1: proto_exercicio.GetResponse.exercicio:type_name -> proto_exercicio.Exercicio
	0,  // 2: proto_exercicio.GetSomesResponse.exercicios:type_name -> proto_exercicio.Exercicio
	1,  // 3: proto_exercicio.ServiceExercicio.Create:input_type -> proto_exercicio.CreateAlterRequest
	1,  // 4: proto_exercicio.ServiceExercicio.Alter:input_type -> proto_exercicio.CreateAlterRequest
	3,  // 5: proto_exercicio.ServiceExercicio.Get:input_type -> proto_exercicio.GetRequest
	5,  // 6: proto_exercicio.ServiceExercicio.GetSomes:input_type -> proto_exercicio.GetSomesRequest
	7,  // 7: proto_exercicio.ServiceExercicio.Delete:input_type -> proto_exercicio.DeleteRequest
	9,  // 8: proto_exercicio.ServiceExercicio.StatusService:input_type -> proto_exercicio.StatusServiceRequest
	2,  // 9: proto_exercicio.ServiceExercicio.Create:output_type -> proto_exercicio.CreateAlterResponse
	2,  // 10: proto_exercicio.ServiceExercicio.Alter:output_type -> proto_exercicio.CreateAlterResponse
	4,  // 11: proto_exercicio.ServiceExercicio.Get:output_type -> proto_exercicio.GetResponse
	6,  // 12: proto_exercicio.ServiceExercicio.GetSomes:output_type -> proto_exercicio.GetSomesResponse
	8,  // 13: proto_exercicio.ServiceExercicio.Delete:output_type -> proto_exercicio.DeleteResponse
	10, // 14: proto_exercicio.ServiceExercicio.StatusService:output_type -> proto_exercicio.StatusServiceResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_exercicio_proto_init() }
func file_grpc_exercicio_proto_init() {
	if File_grpc_exercicio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_exercicio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exercicio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAlterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAlterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSomesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSomesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_exercicio_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_exercicio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_exercicio_proto_goTypes,
		DependencyIndexes: file_grpc_exercicio_proto_depIdxs,
		MessageInfos:      file_grpc_exercicio_proto_msgTypes,
	}.Build()
	File_grpc_exercicio_proto = out.File
	file_grpc_exercicio_proto_rawDesc = nil
	file_grpc_exercicio_proto_goTypes = nil
	file_grpc_exercicio_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceExercicioClient is the client API for ServiceExercicio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceExercicioClient interface {
	Create(ctx context.Context, in *CreateAlterRequest, opts ...grpc.CallOption) (*CreateAlterResponse, error)
	Alter(ctx context.Context, in *CreateAlterRequest, opts ...grpc.CallOption) (*CreateAlterResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetSomes(ctx context.Context, in *GetSomesRequest, opts ...grpc.CallOption) (*GetSomesResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	StatusService(ctx context.Context, in *StatusServiceRequest, opts ...grpc.CallOption) (*StatusServiceResponse, error)
}

type serviceExercicioClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceExercicioClient(cc grpc.ClientConnInterface) ServiceExercicioClient {
	return &serviceExercicioClient{cc}
}

func (c *serviceExercicioClient) Create(ctx context.Context, in *CreateAlterRequest, opts ...grpc.CallOption) (*CreateAlterResponse, error) {
	out := new(CreateAlterResponse)
	err := c.cc.Invoke(ctx, "/proto_exercicio.ServiceExercicio/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceExercicioClient) Alter(ctx context.Context, in *CreateAlterRequest, opts ...grpc.CallOption) (*CreateAlterResponse, error) {
	out := new(CreateAlterResponse)
	err := c.cc.Invoke(ctx, "/proto_exercicio.ServiceExercicio/Alter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceExercicioClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/proto_exercicio.ServiceExercicio/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceExercicioClient) GetSomes(ctx context.Context, in *GetSomesRequest, opts ...grpc.CallOption) (*GetSomesResponse, error) {
	out := new(GetSomesResponse)
	err := c.cc.Invoke(ctx, "/proto_exercicio.ServiceExercicio/GetSomes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceExercicioClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto_exercicio.ServiceExercicio/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceExercicioClient) StatusService(ctx context.Context, in *StatusServiceRequest, opts ...grpc.CallOption) (*StatusServiceResponse, error) {
	out := new(StatusServiceResponse)
	err := c.cc.Invoke(ctx, "/proto_exercicio.ServiceExercicio/StatusService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceExercicioServer is the server API for ServiceExercicio service.
type ServiceExercicioServer interface {
	Create(context.Context, *CreateAlterRequest) (*CreateAlterResponse, error)
	Alter(context.Context, *CreateAlterRequest) (*CreateAlterResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetSomes(context.Context, *GetSomesRequest) (*GetSomesResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	StatusService(context.Context, *StatusServiceRequest) (*StatusServiceResponse, error)
}

// UnimplementedServiceExercicioServer can be embedded to have forward compatible implementations.
type UnimplementedServiceExercicioServer struct {
}

func (*UnimplementedServiceExercicioServer) Create(context.Context, *CreateAlterRequest) (*CreateAlterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedServiceExercicioServer) Alter(context.Context, *CreateAlterRequest) (*CreateAlterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alter not implemented")
}
func (*UnimplementedServiceExercicioServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedServiceExercicioServer) GetSomes(context.Context, *GetSomesRequest) (*GetSomesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSomes not implemented")
}
func (*UnimplementedServiceExercicioServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedServiceExercicioServer) StatusService(context.Context, *StatusServiceRequest) (*StatusServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusService not implemented")
}

func RegisterServiceExercicioServer(s *grpc.Server, srv ServiceExercicioServer) {
	s.RegisterService(&_ServiceExercicio_serviceDesc, srv)
}

func _ServiceExercicio_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExercicioServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_exercicio.ServiceExercicio/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExercicioServer).Create(ctx, req.(*CreateAlterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceExercicio_Alter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExercicioServer).Alter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_exercicio.ServiceExercicio/Alter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExercicioServer).Alter(ctx, req.(*CreateAlterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceExercicio_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExercicioServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_exercicio.ServiceExercicio/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExercicioServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceExercicio_GetSomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSomesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExercicioServer).GetSomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_exercicio.ServiceExercicio/GetSomes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExercicioServer).GetSomes(ctx, req.(*GetSomesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceExercicio_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExercicioServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_exercicio.ServiceExercicio/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExercicioServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceExercicio_StatusService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExercicioServer).StatusService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_exercicio.ServiceExercicio/StatusService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExercicioServer).StatusService(ctx, req.(*StatusServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceExercicio_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_exercicio.ServiceExercicio",
	HandlerType: (*ServiceExercicioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ServiceExercicio_Create_Handler,
		},
		{
			MethodName: "Alter",
			Handler:    _ServiceExercicio_Alter_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ServiceExercicio_Get_Handler,
		},
		{
			MethodName: "GetSomes",
			Handler:    _ServiceExercicio_GetSomes_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ServiceExercicio_Delete_Handler,
		},
		{
			MethodName: "StatusService",
			Handler:    _ServiceExercicio_StatusService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_exercicio.proto",
}
