// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: grpc_prova.proto

package proto_prova

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Aluno struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ra      string `protobuf:"bytes,1,opt,name=ra,proto3" json:"ra,omitempty"`
	Nome    string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Email   string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Celular string `protobuf:"bytes,4,opt,name=celular,proto3" json:"celular,omitempty"`
}

func (x *Aluno) Reset() {
	*x = Aluno{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aluno) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aluno) ProtoMessage() {}

func (x *Aluno) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aluno.ProtoReflect.Descriptor instead.
func (*Aluno) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{0}
}

func (x *Aluno) GetRa() string {
	if x != nil {
		return x.Ra
	}
	return ""
}

func (x *Aluno) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Aluno) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Aluno) GetCelular() string {
	if x != nil {
		return x.Celular
	}
	return ""
}

type Exercicio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome      string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao string `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
	Materia   string `protobuf:"bytes,4,opt,name=materia,proto3" json:"materia,omitempty"`
	Ativo     bool   `protobuf:"varint,5,opt,name=ativo,proto3" json:"ativo,omitempty"`
}

func (x *Exercicio) Reset() {
	*x = Exercicio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exercicio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercicio) ProtoMessage() {}

func (x *Exercicio) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercicio.ProtoReflect.Descriptor instead.
func (*Exercicio) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{1}
}

func (x *Exercicio) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exercicio) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Exercicio) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Exercicio) GetMateria() string {
	if x != nil {
		return x.Materia
	}
	return ""
}

func (x *Exercicio) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

type Prova struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome         string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	DataCadastro *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=dataCadastro,proto3" json:"dataCadastro,omitempty"`
	DataInicio   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=dataInicio,proto3" json:"dataInicio,omitempty"`
	DataFinal    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dataFinal,proto3" json:"dataFinal,omitempty"`
	Serie        string                 `protobuf:"bytes,6,opt,name=serie,proto3" json:"serie,omitempty"`
	Materia      string                 `protobuf:"bytes,7,opt,name=materia,proto3" json:"materia,omitempty"`
	Bimestre     uint32                 `protobuf:"varint,8,opt,name=bimestre,proto3" json:"bimestre,omitempty"`
	Finalizada   bool                   `protobuf:"varint,9,opt,name=finalizada,proto3" json:"finalizada,omitempty"`
	Aluno        *Aluno                 `protobuf:"bytes,10,opt,name=aluno,proto3" json:"aluno,omitempty"`
	Exercicios   []*Exercicio           `protobuf:"bytes,11,rep,name=exercicios,proto3" json:"exercicios,omitempty"`
}

func (x *Prova) Reset() {
	*x = Prova{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prova) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prova) ProtoMessage() {}

func (x *Prova) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prova.ProtoReflect.Descriptor instead.
func (*Prova) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{2}
}

func (x *Prova) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Prova) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Prova) GetDataCadastro() *timestamppb.Timestamp {
	if x != nil {
		return x.DataCadastro
	}
	return nil
}

func (x *Prova) GetDataInicio() *timestamppb.Timestamp {
	if x != nil {
		return x.DataInicio
	}
	return nil
}

func (x *Prova) GetDataFinal() *timestamppb.Timestamp {
	if x != nil {
		return x.DataFinal
	}
	return nil
}

func (x *Prova) GetSerie() string {
	if x != nil {
		return x.Serie
	}
	return ""
}

func (x *Prova) GetMateria() string {
	if x != nil {
		return x.Materia
	}
	return ""
}

func (x *Prova) GetBimestre() uint32 {
	if x != nil {
		return x.Bimestre
	}
	return 0
}

func (x *Prova) GetFinalizada() bool {
	if x != nil {
		return x.Finalizada
	}
	return false
}

func (x *Prova) GetAluno() *Aluno {
	if x != nil {
		return x.Aluno
	}
	return nil
}

func (x *Prova) GetExercicios() []*Exercicio {
	if x != nil {
		return x.Exercicios
	}
	return nil
}

type CreateAlterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prova *Prova `protobuf:"bytes,1,opt,name=prova,proto3" json:"prova,omitempty"`
}

func (x *CreateAlterRequest) Reset() {
	*x = CreateAlterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAlterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlterRequest) ProtoMessage() {}

func (x *CreateAlterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlterRequest.ProtoReflect.Descriptor instead.
func (*CreateAlterRequest) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAlterRequest) GetProva() *Prova {
	if x != nil {
		return x.Prova
	}
	return nil
}

type CreateAlterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateAlterResponse) Reset() {
	*x = CreateAlterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAlterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlterResponse) ProtoMessage() {}

func (x *CreateAlterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlterResponse.ProtoReflect.Descriptor instead.
func (*CreateAlterResponse) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAlterResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateAlterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prova  *Prova `protobuf:"bytes,1,opt,name=prova,proto3" json:"prova,omitempty"`
	Status bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetProva() *Prova {
	if x != nil {
		return x.Prova
	}
	return nil
}

func (x *GetResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetProvaAlunoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdProva uint64 `protobuf:"varint,1,opt,name=id_prova,json=idProva,proto3" json:"id_prova,omitempty"`
	RaAluno string `protobuf:"bytes,2,opt,name=ra_aluno,json=raAluno,proto3" json:"ra_aluno,omitempty"`
}

func (x *GetProvaAlunoRequest) Reset() {
	*x = GetProvaAlunoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProvaAlunoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvaAlunoRequest) ProtoMessage() {}

func (x *GetProvaAlunoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvaAlunoRequest.ProtoReflect.Descriptor instead.
func (*GetProvaAlunoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{7}
}

func (x *GetProvaAlunoRequest) GetIdProva() uint64 {
	if x != nil {
		return x.IdProva
	}
	return 0
}

func (x *GetProvaAlunoRequest) GetRaAluno() string {
	if x != nil {
		return x.RaAluno
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provas []*Prova `protobuf:"bytes,1,rep,name=provas,proto3" json:"provas,omitempty"`
	Status bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error  string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllResponse) GetProvas() []*Prova {
	if x != nil {
		return x.Provas
	}
	return nil
}

func (x *GetAllResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetAllResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusServiceRequest) Reset() {
	*x = StatusServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusServiceRequest) ProtoMessage() {}

func (x *StatusServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusServiceRequest.ProtoReflect.Descriptor instead.
func (*StatusServiceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{12}
}

type StatusServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *StatusServiceResponse) Reset() {
	*x = StatusServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_prova_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusServiceResponse) ProtoMessage() {}

func (x *StatusServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_prova_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusServiceResponse.ProtoReflect.Descriptor instead.
func (*StatusServiceResponse) Descriptor() ([]byte, []int) {
	return file_grpc_prova_proto_rawDescGZIP(), []int{13}
}

func (x *StatusServiceResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *StatusServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_grpc_prova_proto protoreflect.FileDescriptor

var file_grpc_prova_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x5b, 0x0a, 0x05, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x72, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x65, 0x6c, 0x75, 0x6c, 0x61, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x65, 0x6c, 0x75, 0x6c, 0x61, 0x72, 0x22, 0x7d, 0x0a,
	0x09, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x74, 0x69, 0x76, 0x6f, 0x22, 0xaf, 0x03, 0x0a,
	0x05, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x64, 0x61,
	0x74, 0x61, 0x43, 0x61, 0x64, 0x61, 0x73, 0x74, 0x72, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x64, 0x61,
	0x74, 0x61, 0x43, 0x61, 0x64, 0x61, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x3a, 0x0a, 0x0a, 0x64, 0x61,
	0x74, 0x61, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61,
	0x49, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x12, 0x38, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x72, 0x69, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x65, 0x72, 0x69, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x62, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x12, 0x28, 0x0a, 0x05,
	0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x52,
	0x05, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x12, 0x36, 0x0a, 0x0a, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69,
	0x63, 0x69, 0x6f, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63,
	0x69, 0x6f, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x63, 0x69, 0x6f, 0x73, 0x22, 0x3e,
	0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76,
	0x61, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x22, 0x43,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x1c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x65, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x50, 0x72,
	0x6f, 0x76, 0x61, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x76, 0x61, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x69, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x72,
	0x61, 0x5f, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x61, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x22, 0x23, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x6a, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x06, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x76,
	0x61, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x45, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x9b, 0x04, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x12, 0x4d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76,
	0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x05, 0x41, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72,
	0x6f, 0x76, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x41, 0x6c, 0x75,
	0x6e, 0x6f, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x61, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72,
	0x6f, 0x76, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_prova_proto_rawDescOnce sync.Once
	file_grpc_prova_proto_rawDescData = file_grpc_prova_proto_rawDesc
)

func file_grpc_prova_proto_rawDescGZIP() []byte {
	file_grpc_prova_proto_rawDescOnce.Do(func() {
		file_grpc_prova_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_prova_proto_rawDescData)
	})
	return file_grpc_prova_proto_rawDescData
}

var file_grpc_prova_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_grpc_prova_proto_goTypes = []interface{}{
	(*Aluno)(nil),                 // 0: proto_prova.Aluno
	(*Exercicio)(nil),             // 1: proto_prova.Exercicio
	(*Prova)(nil),                 // 2: proto_prova.Prova
	(*CreateAlterRequest)(nil),    // 3: proto_prova.CreateAlterRequest
	(*CreateAlterResponse)(nil),   // 4: proto_prova.CreateAlterResponse
	(*GetRequest)(nil),            // 5: proto_prova.GetRequest
	(*GetResponse)(nil),           // 6: proto_prova.GetResponse
	(*GetProvaAlunoRequest)(nil),  // 7: proto_prova.GetProvaAlunoRequest
	(*GetAllRequest)(nil),         // 8: proto_prova.GetAllRequest
	(*GetAllResponse)(nil),        // 9: proto_prova.GetAllResponse
	(*DeleteRequest)(nil),         // 10: proto_prova.DeleteRequest
	(*DeleteResponse)(nil),        // 11: proto_prova.DeleteResponse
	(*StatusServiceRequest)(nil),  // 12: proto_prova.StatusServiceRequest
	(*StatusServiceResponse)(nil), // 13: proto_prova.StatusServiceResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_grpc_prova_proto_depIdxs = []int32{
	14, // 0: proto_prova.Prova.dataCadastro:type_name -> google.protobuf.Timestamp
	14, // 1: proto_prova.Prova.dataInicio:type_name -> google.protobuf.Timestamp
	14, // 2: proto_prova.Prova.dataFinal:type_name -> google.protobuf.Timestamp
	0,  // 3: proto_prova.Prova.aluno:type_name -> proto_prova.Aluno
	1,  // 4: proto_prova.Prova.exercicios:type_name -> proto_prova.Exercicio
	2,  // 5: proto_prova.CreateAlterRequest.prova:type_name -> proto_prova.Prova
	2,  // 6: proto_prova.GetResponse.prova:type_name -> proto_prova.Prova
	2,  // 7: proto_prova.GetAllResponse.provas:type_name -> proto_prova.Prova
	3,  // 8: proto_prova.ServiceProva.Create:input_type -> proto_prova.CreateAlterRequest
	3,  // 9: proto_prova.ServiceProva.Alter:input_type -> proto_prova.CreateAlterRequest
	5,  // 10: proto_prova.ServiceProva.Get:input_type -> proto_prova.GetRequest
	7,  // 11: proto_prova.ServiceProva.GetProvaAluno:input_type -> proto_prova.GetProvaAlunoRequest
	8,  // 12: proto_prova.ServiceProva.GetAll:input_type -> proto_prova.GetAllRequest
	10, // 13: proto_prova.ServiceProva.Delete:input_type -> proto_prova.DeleteRequest
	12, // 14: proto_prova.ServiceProva.StatusService:input_type -> proto_prova.StatusServiceRequest
	4,  // 15: proto_prova.ServiceProva.Create:output_type -> proto_prova.CreateAlterResponse
	4,  // 16: proto_prova.ServiceProva.Alter:output_type -> proto_prova.CreateAlterResponse
	6,  // 17: proto_prova.ServiceProva.Get:output_type -> proto_prova.GetResponse
	6,  // 18: proto_prova.ServiceProva.GetProvaAluno:output_type -> proto_prova.GetResponse
	9,  // 19: proto_prova.ServiceProva.GetAll:output_type -> proto_prova.GetAllResponse
	11, // 20: proto_prova.ServiceProva.Delete:output_type -> proto_prova.DeleteResponse
	13, // 21: proto_prova.ServiceProva.StatusService:output_type -> proto_prova.StatusServiceResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_grpc_prova_proto_init() }
func file_grpc_prova_proto_init() {
	if File_grpc_prova_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_prova_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aluno); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exercicio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prova); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAlterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAlterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProvaAlunoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_prova_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_prova_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_prova_proto_goTypes,
		DependencyIndexes: file_grpc_prova_proto_depIdxs,
		MessageInfos:      file_grpc_prova_proto_msgTypes,
	}.Build()
	File_grpc_prova_proto = out.File
	file_grpc_prova_proto_rawDesc = nil
	file_grpc_prova_proto_goTypes = nil
	file_grpc_prova_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceProvaClient is the client API for ServiceProva service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceProvaClient interface {
	Create(ctx context.Context, in *CreateAlterRequest, opts ...grpc.CallOption) (*CreateAlterResponse, error)
	Alter(ctx context.Context, in *CreateAlterRequest, opts ...grpc.CallOption) (*CreateAlterResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetProvaAluno(ctx context.Context, in *GetProvaAlunoRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	StatusService(ctx context.Context, in *StatusServiceRequest, opts ...grpc.CallOption) (*StatusServiceResponse, error)
}

type serviceProvaClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceProvaClient(cc grpc.ClientConnInterface) ServiceProvaClient {
	return &serviceProvaClient{cc}
}

func (c *serviceProvaClient) Create(ctx context.Context, in *CreateAlterRequest, opts ...grpc.CallOption) (*CreateAlterResponse, error) {
	out := new(CreateAlterResponse)
	err := c.cc.Invoke(ctx, "/proto_prova.ServiceProva/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvaClient) Alter(ctx context.Context, in *CreateAlterRequest, opts ...grpc.CallOption) (*CreateAlterResponse, error) {
	out := new(CreateAlterResponse)
	err := c.cc.Invoke(ctx, "/proto_prova.ServiceProva/Alter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvaClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/proto_prova.ServiceProva/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvaClient) GetProvaAluno(ctx context.Context, in *GetProvaAlunoRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/proto_prova.ServiceProva/GetProvaAluno", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvaClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/proto_prova.ServiceProva/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvaClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto_prova.ServiceProva/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceProvaClient) StatusService(ctx context.Context, in *StatusServiceRequest, opts ...grpc.CallOption) (*StatusServiceResponse, error) {
	out := new(StatusServiceResponse)
	err := c.cc.Invoke(ctx, "/proto_prova.ServiceProva/StatusService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceProvaServer is the server API for ServiceProva service.
type ServiceProvaServer interface {
	Create(context.Context, *CreateAlterRequest) (*CreateAlterResponse, error)
	Alter(context.Context, *CreateAlterRequest) (*CreateAlterResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetProvaAluno(context.Context, *GetProvaAlunoRequest) (*GetResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	StatusService(context.Context, *StatusServiceRequest) (*StatusServiceResponse, error)
}

// UnimplementedServiceProvaServer can be embedded to have forward compatible implementations.
type UnimplementedServiceProvaServer struct {
}

func (*UnimplementedServiceProvaServer) Create(context.Context, *CreateAlterRequest) (*CreateAlterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedServiceProvaServer) Alter(context.Context, *CreateAlterRequest) (*CreateAlterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alter not implemented")
}
func (*UnimplementedServiceProvaServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedServiceProvaServer) GetProvaAluno(context.Context, *GetProvaAlunoRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvaAluno not implemented")
}
func (*UnimplementedServiceProvaServer) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedServiceProvaServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedServiceProvaServer) StatusService(context.Context, *StatusServiceRequest) (*StatusServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusService not implemented")
}

func RegisterServiceProvaServer(s *grpc.Server, srv ServiceProvaServer) {
	s.RegisterService(&_ServiceProva_serviceDesc, srv)
}

func _ServiceProva_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvaServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_prova.ServiceProva/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvaServer).Create(ctx, req.(*CreateAlterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProva_Alter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvaServer).Alter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_prova.ServiceProva/Alter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvaServer).Alter(ctx, req.(*CreateAlterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProva_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvaServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_prova.ServiceProva/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvaServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProva_GetProvaAluno_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvaAlunoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvaServer).GetProvaAluno(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_prova.ServiceProva/GetProvaAluno",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvaServer).GetProvaAluno(ctx, req.(*GetProvaAlunoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProva_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvaServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_prova.ServiceProva/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvaServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProva_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvaServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_prova.ServiceProva/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvaServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceProva_StatusService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceProvaServer).StatusService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_prova.ServiceProva/StatusService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceProvaServer).StatusService(ctx, req.(*StatusServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceProva_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_prova.ServiceProva",
	HandlerType: (*ServiceProvaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ServiceProva_Create_Handler,
		},
		{
			MethodName: "Alter",
			Handler:    _ServiceProva_Alter_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ServiceProva_Get_Handler,
		},
		{
			MethodName: "GetProvaAluno",
			Handler:    _ServiceProva_GetProvaAluno_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _ServiceProva_GetAll_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ServiceProva_Delete_Handler,
		},
		{
			MethodName: "StatusService",
			Handler:    _ServiceProva_StatusService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_prova.proto",
}
